### PR TITLE
Rebase origin/use-streaming-api

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
Based on this branch https://github.com/y-ken/fluent-plugin-twitter/tree/use-streaming-api

**Comment by okkez** [comment]
I will work to migrate Fluentd v0.14 API after merge this pull request.

**Comment by y-ken** [comment]
Thank you very much!

**Comment by okkez** [comment]
Thank you for quick response! :bow:

**Pull request merged**
