### PR TITLE
Add Ruby 2.3.0 to .travis.yml

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by y-ken** [comment]
Thanks! Would you please add test with multiple fluentd version?
cf. https://github.com/y-ken/fluent-plugin-anonymizer/pull/13

**Comment by okkez** [comment]
OK! :smile:

**Comment by okkez** [comment]
@y-ken I will work after merge this PR.
Thanks!

**Comment by y-ken** [comment]
Do you close this pr?

**Comment by okkez** [comment]
Thanks!

**Pull request closed without merging**
