### PR TITLE
Migrate to Fluentd v0.14 API

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
I will rebase this pull request after merge #29

**Comment by y-ken** [comment]
#29 has merged.

**Comment by okkez** [comment]
Please release new version of this plugin before merge this pull request.

See details: http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12

**Comment by okkez** [comment]
This PR works fine with me.
I've tested both in_twitter and out_twitter using my tokens in real world.

**Comment by y-ken** [comment]
Thank you. But is it problem that td-agent2 user cannot install this plugin after this pr has released?

**Comment by okkez** [comment]
Yes. td-agent2 uses Fluentd 0.12.x not 0.14.x.
You can release new version for td-agent2 (Fluentd v0.12.x) users.
See also: http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12

**Comment by okkez** [comment]
Rebased.

**Comment by y-ken** [comment]
I have released the final version for fluentd v0.12.x as v0.6.0
Thus, would you please fix the conflicts? thank you.

**Comment by y-ken** [comment]
How about keeping backward compatibility like this?
https://github.com/sonots/fluent-plugin-record-reformer/commit/077817a99918e72242a9ad630b6fd3e69b2b84ea

**Comment by okkez** [comment]
> How about keeping backward compatibility like this?

No. It's very bad manner.
It's too hard to keep maintaining both for Fluentd v0.12.x and v0.14.x.

**Comment by okkez** [comment]
Rebased and resolved conflicts.

**Comment by y-ken** [comment]
Today, It has merged! Thank you.

**Pull request merged**
